modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/jaquadro/StorageDrawers/issues"
displayURL="https://minecraft.curseforge.com/projects/storagedrawers"
authors="${mod_authors}"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
